baseurl: "https://bradjanke.com"
languageCode: "en-us"
title: "Brad Janke"
theme: "hugo-tania"
paginate: 6

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji:

  # Logo will show before the blog title on site navbar.
  titleLogo:

  enableLineNos: true
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "Brad Janke"
  siteDesc: ""
  author: "Brad Janke"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email:
    facebook:
    github: https://github.com/bradj
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter: https://twitter.com/bradjanke
    twitch:
    whatsapp:
  
  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: bradj/bradjanke.com
      id: MDEwOlJlcG9zaXRvcnkxMzg5MTk2OQ==
      mapping: title
      reactionsEnabled: 1
      emitMetadata: 0
      category:
        name: Comments
        id: DIC_kwDOANP5gc4COU5v

menu:
  header:
    - name: Articles
      url: "/articles/"
    - name: About
      url: "/about/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
