baseurl = "https://bradjanke.com/"
title = "Brad Janke"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = false # Allow user HTML tags

[params]
    author = "Brad Janke"
    avatar = "headshot.jpg"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    description = """
        Infrastructure, ramblings, and software.

    """
    publicationYear = "2022"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "about"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-info-circle fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/about/"
    weight = 10

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/bradj"
    weight = 20

[[menu.main]]
    identifier = "keybase"
    pre = "<i class='fab fa-keybase fa-lg'></i>"
    url = "https://keybase.io/bradj"
    weight = 30

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/bradjanke"
    weight = 30
