name: Build & Publish

on:
  push:

jobs:
  build-test-publish:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Get Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_0.68.3_Linux-64bit.tar.gz
          tar xvf hugo_0.68.3_Linux-64bit.tar.gz

      - name: Hugo Build
        run: |
          ./hugo -D
